export const ENTRIES_CONSTANTS = {
  AUTOSAVE_DELAY_MS: 500,
  FOCUS_MODE_FADE_DELAY_MS: 2000,
  FOCUS_MODE_EDGE_THRESHOLD_PX: 150,

  SIDEBAR_WIDTH_COLLAPSED: 48,
  SIDEBAR_WIDTH_EXPANDED: 300,

  HEADER_HEIGHT_PX: 40,
  ENTRY_ITEM_HEIGHT_PX: 64,

  PAGINATION_THRESHOLD: 10,
  LOADING_INDICATOR_HEIGHT_PX: 40,

  TOOLBAR_BUTTON_SIZE: 32,
  TOOLBAR_BUTTON_SIZE_SMALL: 28,

  DATE_PICKER_FROM_YEAR: 2020,
  DATE_PICKER_TO_YEAR: 2030,
} as const;

export const MOBILE_ENTRIES_CONSTANTS = {
  SWIPE_EDGE_WIDTH: 40,
  SWIPE_THRESHOLD: 70,
  SEARCH_BAR_HEIGHT: 60,
  FAB_BOTTOM_OFFSET: 16,
} as const;
